=== 161250205/ApplicationIntegration/xsd/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jw.nju.edu.cn/schema/info"
        xmlns:tns="http://jw.nju.edu.cn/schema/info"
        elementFormDefault="qualified">

    <element name="infoList" type="tns:infoListType"/>

    <!--单个航班信息类型-->
    <complexType name="infoType">
        <all>
            <element name="company" type="tns:airlineCompanyType"/>
            <element name="flightNumber" type="tns:flightNumberType"/>
            <element name="departureAirport" type="tns:airportNameType"/>
            <element name="arrivalAirport" type="tns:airportNameType"/>
            <element name="departureTime" type="tns:hourMinutes"/>
            <element name="arrivalTime" type="tns:hourMinutes"/>
            <element name="price" type="tns:flightPriceType"/>
        </all>
    </complexType>

    <!--航班信息列表类型, 以携程途牛去哪儿平台为单位-->
    <complexType name="infoListType">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <element name="info" type="tns:infoType"/>
        </sequence>
        <attribute name="company" type="tns:platformCompanyType"/>
    </complexType>

    <!--平台, 枚举-->
    <simpleType name="platformCompanyType">
        <restriction base="string">
            <enumeration value="携程"/>
            <enumeration value="途牛"/>
            <enumeration value="去哪儿"/>
        </restriction>
    </simpleType>

    <!--航空公司, 自由字符串-->
    <simpleType name="airlineCompanyType">
        <restriction base="string">
            <!--<enumeration value="东方航空"/>-->
            <!--<enumeration value="厦门航空"/>-->
            <!--<enumeration value="海南航空"/>-->
            <!--<enumeration value="中国国航"/>-->
            <!--<enumeration value="上海航空"/>-->
            <!--<enumeration value="中国联航"/>-->
            <!--<enumeration value="金鹏航空"/>-->
        </restriction>
    </simpleType>

    <!--航班号, 机号, 字母数字限定-->
    <simpleType name="flightNumberType">
        <restriction base="string">
            <pattern value="[a-zA-Z0-9]*"/>
        </restriction>
    </simpleType>

    <!--机场名字, 暂时不设限定-->
    <simpleType name="airportNameType">
        <restriction base="string"/>
    </simpleType>

    <!--航班价格, 正整数-->
    <simpleType name="flightPriceType">
        <restriction base="int">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

    <simpleType name="hourMinutes">
        <restriction base="string">
            <pattern value="[0-9]{2}:[0-9]{2}"/>
        </restriction>
    </simpleType>
</schema>

=== 161250205/ApplicationIntegration/tn/x.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<infoList xmlns="http://jw.nju.edu.cn/schema/info" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" company="途牛" xsi:schemaLocation="http://jw.nju.edu.cn/schema/info https://raw.githubusercontent.com/161250205/ApplicationIntegration/master/xsd/xsd.xsd">
    <info>
        <company>中国东方航空</company>
        <flightNumber>MU5128</flightNumber>
        <departureTime>21:05</departureTime>
        <departureAirport>首都T2</departureAirport>
        <arrivalTime>23:20</arrivalTime>
        <arrivalAirport>虹桥T2</arrivalAirport>
        <price>570</price>
    </info>
    <info><company>中国东方航空</company><flightNumber>MU5158</flightNumber><departureTime>21:30</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>23:45</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>570</price></info><info><company>中国东方航空</company><flightNumber>MU5160</flightNumber><departureTime>21:50</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>23:55</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>570</price></info><info><company>中国东方航空</company><flightNumber>MU4682</flightNumber><departureTime>06:50</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>09:05</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>930</price></info><info><company>吉祥航空</company><flightNumber>HO1252</flightNumber><departureTime>06:50</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>09:05</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>830</price></info><info><company>中国国际航空</company><flightNumber>CA3202</flightNumber><departureTime>06:50</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>09:05</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>980</price></info><info><company>中国东方航空</company><flightNumber>MU5138</flightNumber><departureTime>07:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>09:20</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>830</price></info><info><company>深圳航空</company><flightNumber>ZH1831</flightNumber><departureTime>07:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>09:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国国际航空</company><flightNumber>CA1831</flightNumber><departureTime>07:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>09:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国东方航空</company><flightNumber>MU5183</flightNumber><departureTime>07:35</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>09:50</arrivalTime><arrivalAirport>浦东T1</arrivalAirport><price>830</price></info><info><company>海南航空</company><flightNumber>HU7611</flightNumber><departureTime>07:40</departureTime><departureAirport>首都T1</departureAirport><arrivalTime>09:55</arrivalTime><arrivalAirport>浦东T2</arrivalAirport><price>800</price></info><info><company>金鹏航空</company><flightNumber>Y87611</flightNumber><departureTime>07:40</departureTime><departureAirport>首都T1</departureAirport><arrivalTime>09:55</arrivalTime><arrivalAirport>浦东T2</arrivalAirport><price>1130</price></info><info><company>海南航空</company><flightNumber>HU7605</flightNumber><departureTime>07:45</departureTime><departureAirport>首都T1</departureAirport><arrivalTime>10:00</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>800</price></info><info><company>中国东方航空</company><flightNumber>MU3813</flightNumber><departureTime>07:50</departureTime><departureAirport>南苑</departureAirport><arrivalTime>09:50</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1290</price></info><info><company>联合航空</company><flightNumber>KN5737</flightNumber><departureTime>07:50</departureTime><departureAirport>南苑</departureAirport><arrivalTime>09:50</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1008</price></info><info><company>中国东方航空</company><flightNumber>MU5102</flightNumber><departureTime>08:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>10:15</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>980</price></info><info><company>中国南方航空</company><flightNumber>CZ3907</flightNumber><departureTime>08:15</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>10:30</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1240</price></info><info><company>厦门航空</company><flightNumber>MF1367</flightNumber><departureTime>08:15</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>10:30</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1240</price></info><info><company>中国东方航空</company><flightNumber>MU3210</flightNumber><departureTime>08:15</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>10:30</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国国际航空</company><flightNumber>CA1501</flightNumber><departureTime>08:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>10:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>深圳航空</company><flightNumber>ZH1501</flightNumber><departureTime>08:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>10:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国东方航空</company><flightNumber>MU5156</flightNumber><departureTime>08:30</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>10:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>670</price></info><info><company>海南航空</company><flightNumber>HU7607</flightNumber><departureTime>08:45</departureTime><departureAirport>首都T1</departureAirport><arrivalTime>11:00</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>890</price></info><info><company>中国东方航空</company><flightNumber>MU5104</flightNumber><departureTime>09:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>11:15</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>980</price></info><info><company>深圳航空</company><flightNumber>ZH1519</flightNumber><departureTime>09:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>11:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国国际航空</company><flightNumber>CA1519</flightNumber><departureTime>09:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>11:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国东方航空</company><flightNumber>MU5106</flightNumber><departureTime>10:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>12:15</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>980</price></info><info><company>中国国际航空</company><flightNumber>CA1531</flightNumber><departureTime>10:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>12:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>深圳航空</company><flightNumber>ZH1531</flightNumber><departureTime>10:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>12:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>吉祥航空</company><flightNumber>HO3610</flightNumber><departureTime>11:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>13:20</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1130</price></info><info><company>中国东方航空</company><flightNumber>MU5108</flightNumber><departureTime>11:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>13:20</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>980</price></info><info><company>深圳航空</company><flightNumber>ZH1557</flightNumber><departureTime>11:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>13:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国国际航空</company><flightNumber>CA1557</flightNumber><departureTime>11:30</departureTime><departureAirport>首都T3</departureAirport><arrivalTime>13:40</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1490</price></info><info><company>中国东方航空</company><flightNumber>MU5152</flightNumber><departureTime>11:30</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>14:00</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>830</price></info><info><company>联合航空</company><flightNumber>KN5977</flightNumber><departureTime>11:55</departureTime><departureAirport>南苑</departureAirport><arrivalTime>14:05</arrivalTime><arrivalAirport>浦东T1</arrivalAirport><price>1008</price></info><info><company>中国东方航空</company><flightNumber>MU3843</flightNumber><departureTime>11:55</departureTime><departureAirport>南苑</departureAirport><arrivalTime>14:05</arrivalTime><arrivalAirport>浦东T1</arrivalAirport><price>1290</price></info><info><company>中国东方航空</company><flightNumber>MU5110</flightNumber><departureTime>12:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>14:20</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>830</price></info><info><company>中国东方航空</company><flightNumber>MU271</flightNumber><departureTime>12:55</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>15:20</arrivalTime><arrivalAirport>浦东T1</arrivalAirport><price>1480</price></info><info><company>中国东方航空</company><flightNumber>MU5112</flightNumber><departureTime>13:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>15:15</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>830</price></info><info><company>吉祥航空</company><flightNumber>HO3604</flightNumber><departureTime>13:00</departureTime><departureAirport>首都T2</departureAirport><arrivalTime>15:15</arrivalTime><arrivalAirport>虹桥T2</arrivalAirport><price>1130</price></info><info><company>中国东方航空</company><flightNumber>MU8560</flightNumber><departureTime>13:05</departureTime><departureAirport>首都T2</departureAirport><arr
